import React, { useState, useEffect } from 'react';

const Service = () => {
  const [first, editFirst] = useState("Heading 1");
  const [second, editSecond] = useState("Heading 2");

  useEffect(() => {
    console.log("Mounted Component");
    
    return () => {
      console.log("Unponted Component");
    };
  }, [second]);

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      {/* Box 1 - Simple Update */}
      <div style={{ background: '#e0f2fe', padding: '15px', border: '2px solid #0ea5e9', borderRadius: '8px', marginBottom: '20px' }}>
        <h1 style={{ margin: '0' }}>{first}</h1>
        <p style={{ fontSize: '14px' }}>
          Clicking the button below only updates this text. 
          React is just doing "Updation" here. The console stays quiet!
        </p>
        <button 
          onClick={() => editFirst("I changed Box 1!")}
          style={{ marginTop: '10px', padding: '8px 16px', cursor: 'pointer' ,backgroundColor:'white'}}
        >
          Update Box 1
        </button>
      </div>

      
      <div style={{ background: '#dcfce7', padding: '15px', border: '2px solid #22c55e', borderRadius: '8px', marginBottom: '20px' }}>
        <h2 style={{ margin: '0' }}>{second}</h2>
        <p style={{ fontSize: '14px' }}>
          Clicking this makes the <b>useEffect</b> restart. 
          Check the console: You'll see the "Stopping" log then the "Starting" log.
        </p>
        <button 
          onClick={() => editSecond("I triggered the Watcher!")}
          style={{ marginTop: '10px', padding: '8px 16px', cursor: 'pointer' ,backgroundColor:'white' }}
        >
          Update Box 2
        </button>
      </div>

      
      <div style={{ marginTop: '30px', borderTop: '1px solid #ddd', paddingTop: '20px' }}>
        <h1 className="text-3xl text-bold p-4">Below Content is generated by LLM model , what i explained to it.</h1>
        <p><b>Wait, did the whole app refresh?</b> No. If the app refreshed, console would clear and the screen would blink white. That's NOT what happens.</p>

        <p><b>What is "Re-rendering" then?</b> It's just the function <code>Service()</code> running again to see if <code>first</code> or <code>second</code> has a new value. That's it.</p>

        <p><b>Why did the console log Unmount?</b> Because when you change <code>second</code>, the old "Effect" has to be cleaned up before the new "Effect" starts. It's like erasing a whiteboard before writing on it again.</p>
      </div>
    </div>
  );
};

export default Service;